# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nau < Formula
  desc "Modular project management tool."
  homepage "https://github.com/antonio-leitao/homebrew-taps"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.2/nau_Darwin_arm64.tar.gz"
      sha256 "7bbca6066b61186fd206a9e3476ed2dea0dadb6f163ed74d4eb3acb536baf358"

      def install
        bin.install "nau"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.2/nau_Darwin_x86_64.tar.gz"
      sha256 "14249425435cd03b3c4e6e769cd1a2a04283a15a202730b6d52b24b16571fc66"

      def install
        bin.install "nau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.2/nau_Linux_arm64.tar.gz"
      sha256 "21bbfc806a91980df82fda36a93792a0bc33de8609babee14a8b96967aba9e9d"

      def install
        bin.install "nau"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.2/nau_Linux_x86_64.tar.gz"
      sha256 "d28774ab0378bf4b111a588b96685edf3680c6cf6688b872079789df0999a22a"

      def install
        bin.install "nau"
      end
    end
  end
end
