# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nau < Formula
  desc "Modular project management tool."
  homepage "https://github.com/antonio-leitao/homebrew-taps"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.1/nau_Darwin_arm64.tar.gz"
      sha256 "7cdb9b5bc53f3975ef143d5b88e3ec2564866c0c142252f8de7d8c78629a15cb"

      def install
        bin.install "nau"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.1/nau_Darwin_x86_64.tar.gz"
      sha256 "21a73aa5580d9a782a9c736d4e9fc775de8031138dad826ca2a7f1c8d46fd7cb"

      def install
        bin.install "nau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.1/nau_Linux_arm64.tar.gz"
      sha256 "1a207e54da6a9fae14c65778dc2c2962aa8d94fcda7f10e8c49193b32ad78e0c"

      def install
        bin.install "nau"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/antonio-leitao/nau/releases/download/v0.1.1/nau_Linux_x86_64.tar.gz"
      sha256 "8d9fe5d03cbc4d1417b3fafba4a9fee7e2a97ea9ed201b7dfb6b589bcc9f84ed"

      def install
        bin.install "nau"
      end
    end
  end
end
